### ISSUE TITLE
BPM Event Input does not appear

### ISSUE THREAD

**Issue by DolphinDTM** [excln/BmsONE#6]
When I click to add a new BPM event, the toolbar to input new BPM does not appear as it should, based on the instructions of the official website:

>  "To edit BPM events, click on the lane next to measures bar. After placing or selecting a BPM event, a small tool bar to input BPM appears."

Currently it just places a BPM event with the same value as the initial BPM.

**Comment by excln** [comment]
Thanks, that is a bug since beta 0.1.5 and will be fixed in the next version. Yet you can manually make BPM event input window appear by `View` -> `Views` -> `Selected Objects` from menu bar now. The instructions also need to be updated: `tool bar` -> `window`

**Comment by excln** [comment]
Fixed at [beta 0.2.1](https://github.com/excln/BmsONE/releases/tag/beta_021).
